"use client";
import {useEffect,useMemo,useRef,useState} from "react";
import * as XLSX from "xlsx";
import {supabase} from "../lib/supabase";
import {Search,Phone,MessageCircle,Plus,Upload,Check,Clock,AlertTriangle,LogOut,FolderOpen,RefreshCw,FileText,CalendarDays,Activity as ActivityIcon,Download,Trash2,CheckSquare,Edit3,X,Save,Settings,ExternalLink} from "lucide-react";

type Lead={id:string;user_id:string;folder_id:string|null;client_name:string|null;business_name:string;category:string|null;phone:string|null;whatsapp:string|null;email:string|null;website:string|null;instagram:string|null;address:string|null;city:string|null;state:string|null;country:string|null;source:string|null;status:string;priority:string;notes:string|null;last_contacted_at:string|null;created_at:string;call_attempts:number;last_call_outcome:string|null};
type Folder={id:string;name:string;icon:string;color:string;description:string|null};
type Followup={id:string;lead_id:string;title:string;description:string|null;scheduled_at:string;completed:boolean};
type Template={id:string;folder_id:string|null;phase_number:number;title:string;message:string};

const statuses=["New","Pending","Contacted","Follow-up","Interested","Not Interested","No Response","Wrong Number","Converted","Closed"];
const priorities=["Low","Medium","High","Urgent"]; const outcomes=["Called","No Answer","Busy","Call Back","Wrong Number"];
const fields=["client_name","business_name","category","phone","whatsapp","email","website","instagram","address","city","state","country","source","notes"];

function val(s:any,k:string){return s?.[k]===undefined||s?.[k]===null?"":String(s[k]);}
function wa(n:string){return n.replace(/\D/g,"").replace(/^0/,"91");}
function personalize(t:string,l:Lead){return t.replace(/\{\{client_name\}\}/g,l.client_name||"").replace(/\{\{business_name\}\}/g,l.business_name).replace(/\{\{city\}\}/g,l.city||"").replace(/\{\{category\}\}/g,l.category||"");}

export default function Home(){
 const [user,setUser]=useState<any>(null),[leads,setLeads]=useState<Lead[]>([]),[folders,setFolders]=useState<Folder[]>([]),[followups,setFollowups]=useState<Followup[]>([]),[templates,setTemplates]=useState<Template[]>([]),[activities,setActivities]=useState<any[]>([]);
 const [q,setQ]=useState(""),[status,setStatus]=useState(""),[folder,setFolder]=useState(""),[busy,setBusy]=useState(true),[tab,setTab]=useState("dashboard"),[page,setPage]=useState(1),[selected,setSelected]=useState<Lead|null>(null),[toast,setToast]=useState("");
 const [showImport,setShowImport]=useState(false),[showFolder,setShowFolder]=useState(false),[showTemplate,setShowTemplate]=useState(false),[showFollowup,setShowFollowup]=useState(false),[phaseLead,setPhaseLead]=useState<Lead|null>(null),[callLead,setCallLead]=useState<Lead|null>(null);
 const [note,setNote]=useState(""),[newFolder,setNewFolder]=useState(""),[newTemplate,setNewTemplate]=useState({title:"",message:"",folder_id:"",phase_number:1}),[follow,setFollow]=useState({title:"",description:"",scheduled_at:""}); const [progress,setProgress]=useState<any[]>([]),[notes,setNotes]=useState<any[]>([]); const [selectedIds,setSelectedIds]=useState<string[]>([]); const [showSettings,setShowSettings]=useState(false),[editTemplate,setEditTemplate]=useState<any>(null),[editFollowup,setEditFollowup]=useState<any>(null); const [apiConfigs,setApiConfigs]=useState<any[]>([]); const [importRows,setImportRows]=useState<any[]>([]),[importMode,setImportMode]=useState("skip");
 const input=useRef<HTMLInputElement>(null);

 async function load(u:any){
  setBusy(true);
  const [l,f,fu,t,a,p,n,ac]=await Promise.all([
   supabase.from("leads").select("*").order("created_at",{ascending:false}),
   supabase.from("folders").select("id,name,icon,color,description").order("name"),
   supabase.from("followups").select("*").order("scheduled_at"),
   supabase.from("message_templates").select("*").order("folder_id").order("phase_number"),
   supabase.from("lead_activities").select("*").order("created_at",{ascending:false}).limit(100),
   supabase.from("lead_message_progress").select("*").order("phase_number"),
   supabase.from("notes").select("*").order("created_at",{ascending:false}).limit(100),
   supabase.from("api_configs").select("*").order("created_at",{ascending:false})
  ]);
  if(l.data)setLeads(l.data);if(f.data)setFolders(f.data);if(fu.data)setFollowups(fu.data);if(t.data)setTemplates(t.data);if(a.data)setActivities(a.data);if(p.data)setProgress(p.data);if(n.data)setNotes(n.data);if(ac.data)setApiConfigs(ac.data);setBusy(false);
 }
 useEffect(()=>{supabase.auth.getUser().then(({data})=>{if(data.user){setUser(data.user);load(data.user)}else window.location.href="/f_/login/"});const {data}=supabase.auth.onAuthStateChange((_,s)=>{if(s?.user)setUser(s.user);});return()=>data.subscription.unsubscribe()},[]);

 const filtered=useMemo(()=>leads.filter(l=>(!q||[l.business_name,l.client_name,l.phone,l.whatsapp,l.email,l.city,l.state].join(" ").toLowerCase().includes(q.toLowerCase()))&&(!status||l.status===status)&&(!folder||l.folder_id===folder)),[leads,q,status,folder]); const pageSize=50; const pageCount=Math.max(1,Math.ceil(filtered.length/pageSize)); const pageLeads=filtered.slice((page-1)*pageSize,page*pageSize);
 const today=new Date(); const due=followups.filter(x=>!x.completed&&new Date(x.scheduled_at)<=today); const todayCount=followups.filter(x=>!x.completed&&new Date(x.scheduled_at).toDateString()===today.toDateString()).length;
 const stats={total:leads.length,new:leads.filter(x=>x.status==="New").length,contacted:leads.filter(x=>["Contacted","Follow-up","Interested","Converted"].includes(x.status)).length,interested:leads.filter(x=>x.status==="Interested").length,converted:leads.filter(x=>x.status==="Converted").length};

 function notify(s:string){setToast(s);setTimeout(()=>setToast(""),2500)}
 async function activity(lead_id:string,type:string,description:string){await supabase.from("lead_activities").insert({lead_id,user_id:user.id,type,title:type,description});}
 async function call(lead:Lead,outcome?:string){window.location.href=`tel:${lead.phone||lead.whatsapp||""}`;await supabase.from("leads").update({last_contacted_at:new Date().toISOString(),call_attempts:(lead.call_attempts||0)+1,last_call_outcome:outcome||"Called",status:outcome==="Wrong Number"?"Wrong Number":outcome==="Call Back"?"Follow-up":(outcome==="No Answer"||outcome==="Busy")?"No Response":"Contacted"}).eq("id",lead.id);await activity(lead.id,"call",`Call outcome: ${outcome||"Called"}`);await load(user);notify("Call activity recorded");}
 async function openWA(lead:Lead,t:Template){const msg=personalize(t.message,lead);window.open(`https://wa.me/${wa(lead.whatsapp||lead.phone||"")}?text=${encodeURIComponent(msg)}`,"_blank");await supabase.from("lead_message_progress").insert({lead_id:lead.id,template_id:t.id,phase_number:t.phase_number,state:"opened",opened_at:new Date().toISOString()});await activity(lead.id,"whatsapp",`WhatsApp Phase ${t.phase_number} initiated`);notify("WhatsApp opened. Press Send manually.");}
 async function confirmSent(p:any){await supabase.from("lead_message_progress").update({state:"confirmed_sent",confirmed_sent_at:new Date().toISOString()}).eq("id",p.id);await activity(p.lead_id,"whatsapp",`Phase ${p.phase_number} marked as sent`);await load(user);notify("WhatsApp phase marked sent");}
 function sentCount(leadId:string){return progress.filter(p=>p.lead_id===leadId&&p.state==="confirmed_sent").reduce((m,p)=>Math.max(m,p.phase_number),0)}
 async function addFolder(){if(!newFolder.trim())return;await supabase.from("folders").insert({user_id:user.id,name:newFolder.trim()});setNewFolder("");setShowFolder(false);await load(user);notify("Folder created");}
 async function addTemplate(){const payload={...newTemplate,user_id:user.id,folder_id:newTemplate.folder_id||null};const res=editTemplate?await supabase.from("message_templates").update(payload).eq("id",editTemplate.id):await supabase.from("message_templates").insert(payload);if(res.error)return notify(res.error.message);setShowTemplate(false);setEditTemplate(null);setNewTemplate({title:"",message:"",folder_id:"",phase_number:1});await load(user);notify(editTemplate?"Template updated":"Template created")}
 async function deleteTemplate(t:any){if(!confirm("Delete this phase?"))return;await supabase.from("message_templates").delete().eq("id",t.id);await load(user)}
 function startEditTemplate(t:any){setEditTemplate(t);setNewTemplate({title:t.title,message:t.message,folder_id:t.folder_id||"",phase_number:t.phase_number});setShowTemplate(true)}
 async function addFollow(){if(!selected)return;const payload={title:follow.title,description:follow.description||null,scheduled_at:new Date(follow.scheduled_at).toISOString()};const res=editFollowup?await supabase.from("followups").update(payload).eq("id",editFollowup.id):await supabase.from("followups").insert({...payload,lead_id:selected.id,user_id:user.id});if(res.error)return notify(res.error.message);if(!editFollowup)await activity(selected.id,"followup","Follow-up scheduled");setFollow({title:"",description:"",scheduled_at:""});setEditFollowup(null);setShowFollowup(false);await load(user)}
 async function complete(f:Followup){await supabase.from("followups").update({completed:!f.completed}).eq("id",f.id);await activity(f.lead_id,"followup",f.completed?"Follow-up reopened":"Follow-up completed");await load(user)}
 function startEditFollowup(f:any){setSelected(leads.find(l=>l.id===f.lead_id)||null);setEditFollowup(f);setFollow({title:f.title,description:f.description||"",scheduled_at:new Date(f.scheduled_at).toISOString().slice(0,16)});setShowFollowup(true)}
 async function saveNote(){if(!selected||!note.trim())return;await supabase.from("notes").insert({lead_id:selected.id,user_id:user.id,content:note.trim()});await activity(selected.id,"note","Note added");setNote("");notify("Note saved");}
 async function statusChange(lead:Lead,s:string){await supabase.from("leads").update({status:s}).eq("id",lead.id);await activity(lead.id,"status",`Status changed to ${s}`);await load(user);}
 async function importFile(file:File){const buf=await file.arrayBuffer();const wb=XLSX.read(buf,{type:"array"});const rows=XLSX.utils.sheet_to_json<any>(wb.Sheets[wb.SheetNames[0]],{defval:""});setImportRows(rows.slice(0,1000));}
 function exportCSV(){const cols=["business_name","client_name","category","phone","whatsapp","email","website","instagram","address","city","state","country","source","status","priority","call_attempts","last_call_outcome","last_contacted_at","notes"];const esc=(v:any)=>`"${String(v??"").replace(/"/g,`""`)}"`;const csv=[cols.join(","),...leads.map(l=>cols.map(k=>esc((l as any)[k])).join(","))].join("\n");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([csv],{type:"text/csv"}));a.download=`leadflow-${new Date().toISOString().slice(0,10)}.csv`;a.click();URL.revokeObjectURL(a.href)}
 async function bulkStatus(s:string){if(!selectedIds.length)return notify("Select leads first");await supabase.from("leads").update({status:s}).in("id",selectedIds);setSelectedIds([]);await load(user);notify("Bulk status updated")}
 async function bulkPriority(p:string){if(!selectedIds.length)return notify("Select leads first");await supabase.from("leads").update({priority:p}).in("id",selectedIds);setSelectedIds([]);await load(user);notify("Bulk priority updated")}
 async function bulkFolder(f:string){if(!selectedIds.length)return notify("Select leads first");await supabase.from("leads").update({folder_id:f||null}).in("id",selectedIds);setSelectedIds([]);await load(user);notify("Bulk folder updated")}
 async function bulkDelete(){if(!selectedIds.length||!confirm(`Delete ${selectedIds.length} selected leads?`))return;await supabase.from("leads").delete().in("id",selectedIds);setSelectedIds([]);await load(user);notify("Selected leads deleted")}
 async function signout(){await supabase.auth.signOut();window.location.href="/f_/login/";}

 return <div className="min-h-screen">
 {toast&&<div className="fixed right-5 top-5 z-50 card px-4 py-3 text-sm">{toast}</div>}
 {due.length>0&&<div className="border-b border-red-900 bg-red-950/50 px-5 py-3 text-red-200"><div className="font-semibold flex items-center gap-2"><AlertTriangle size={16}/>ACTION REQUIRED: {due.length} overdue/uncompleted follow-up{due.length>1?"s":""}</div><div className="text-xs mt-1">{due.slice(0,3).map(x=>x.title).join(" • ")}</div></div>}
 <div className="flex min-h-[calc(100vh-0px)]">
  <aside className="hidden md:block w-60 border-r border-slate-800 p-4 bg-[#090d13]"><div className="text-xl font-semibold mb-7">LeadFlow</div>
   {["dashboard","leads","folders","followups","templates","activity"].map(x=><button key={x} onClick={()=>setTab(x)} className={`w-full text-left px-3 py-2 rounded-lg mb-1 capitalize ${tab===x?"bg-blue-600":"hover:bg-slate-900"}`}>{x==="followups"?`Today's Follow-ups`:x}</button>)}
   <button onClick={()=>setShowImport(true)} className="w-full text-left px-3 py-2 rounded-lg mb-1 hover:bg-slate-900">Import Leads</button>
   <button onClick={signout} className="w-full text-left px-3 py-2 rounded-lg mt-6 muted flex gap-2"><LogOut size={16}/>Sign out</button>
  </aside>
  <main className="flex-1 min-w-0 p-4 md:p-7">
   <header className="flex flex-col md:flex-row gap-3 justify-between mb-6"><div><h1 className="text-2xl font-semibold capitalize">{tab}</h1><p className="muted text-sm">{user?.email}</p></div><div className="flex gap-2"><div className="relative"><Search size={16} className="absolute left-3 top-3 muted"/><input className="field pl-9 w-64" placeholder="Search leads…" value={q} onChange={e=>{setQ(e.target.value);setPage(1)}}/></div><button className="btn" onClick={()=>load(user)}><RefreshCw size={16}/></button></div></header>

   {tab==="dashboard"&&<><div className="grid grid-cols-2 lg:grid-cols-5 gap-3">{[["Total Leads",stats.total],["New",stats.new],["Contacted",stats.contacted],["Interested",stats.interested],["Converted",stats.converted]].map(x=><div className="card p-4" key={x[0]}><div className="muted text-xs">{x[0]}</div><div className="text-2xl mt-2">{x[1]}</div></div>)}</div>
    <div className="grid lg:grid-cols-2 gap-4 mt-4"><section className="card p-5"><h2 className="font-semibold mb-4">Today's Follow-ups</h2>{followups.filter(x=>!x.completed&&new Date(x.scheduled_at).toDateString()===today.toDateString()).slice(0,8).map(f=><div key={f.id} className="border-b border-slate-800 py-3 flex justify-between"><div><div>{f.title}</div><div className="muted text-xs">{new Date(f.scheduled_at).toLocaleString("en-IN")}</div></div><button className="btn" onClick={()=>complete(f)}><Check size={15}/></button></div>)}{todayCount===0&&<div className="muted text-sm">No follow-ups today.</div>}</section>
    <section className="card p-5"><h2 className="font-semibold mb-4">Folder Overview</h2>{folders.map(f=><div key={f.id} className="flex justify-between py-2 border-b border-slate-800"><span>{f.name}</span><span className="muted">{leads.filter(l=>l.folder_id===f.id).length}</span></div>)}{!folders.length&&<div className="muted text-sm">No folders yet.</div>}</section></div></>}

   {(tab==="leads"||tab==="dashboard")&&<section className="card mt-4 overflow-hidden"><div className="p-4 flex gap-2 border-b border-slate-800 flex-wrap"><button className="btn" onClick={exportCSV}><Download size={15}/>Export CSV</button>{selectedIds.length>0&&<><span className="btn">{selectedIds.length} selected</span><select className="field w-auto" defaultValue="" onChange={e=>e.target.value&&bulkStatus(e.target.value)}><option value="">Status…</option>{statuses.map(s=><option key={s}>{s}</option>)}</select><select className="field w-auto" defaultValue="" onChange={e=>e.target.value&&bulkPriority(e.target.value)}><option value="">Priority…</option>{priorities.map(p=><option key={p}>{p}</option>)}</select><select className="field w-auto" defaultValue="" onChange={e=>bulkFolder(e.target.value)}><option value="">Move folder…</option>{folders.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select><button className="btn text-red-300" onClick={bulkDelete}><Trash2 size={14}/>Delete</button></>} <select className="field w-auto" value={status} onChange={e=>{setStatus(e.target.value);setPage(1)}}><option value="">All statuses</option>{statuses.map(s=><option key={s}>{s}</option>)}</select><select className="field w-auto" value={folder} onChange={e=>{setFolder(e.target.value);setPage(1)}}><option value="">All folders</option>{folders.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select><button className="btn ml-auto" onClick={()=>setShowFolder(true)}><Plus size={16}/>Folder</button></div>
   <div className="overflow-auto"><table className="w-full text-sm"><thead><tr className="text-left muted border-b border-slate-800"><th className="p-3"><button onClick={()=>setSelectedIds(selectedIds.length===filtered.length?[]:filtered.map(x=>x.id))}><CheckSquare size={15}/></button></th><th>Business</th><th>Contact</th><th>Phone</th><th>Progress</th><th>Status</th><th>Priority</th><th>Actions</th></tr></thead><tbody>{pageLeads.map(l=><tr key={l.id} className="border-b border-slate-800/70 hover:bg-slate-900/50"><td className="p-3"><input type="checkbox" checked={selectedIds.includes(l.id)} onChange={()=>setSelectedIds(x=>x.includes(l.id)?x.filter(id=>id!==l.id):[...x,l.id])}/></td><td className="p-3"><button className="font-medium text-blue-300" onClick={()=>setSelected(l)}>{l.business_name}</button><div className="muted text-xs">{l.category||"—"} · {l.city||"—"}</div></td><td>{l.client_name||"—"}</td><td>{l.phone||l.whatsapp||"—"}</td><td className="text-xs">{sentCount(l.id)}/{templates.filter(t=>t.folder_id===l.folder_id||t.folder_id===null).length}</td><td><select className="bg-transparent" value={l.status} onChange={e=>statusChange(l,e.target.value)}>{statuses.map(s=><option className="bg-slate-900" key={s}>{s}</option>)}</select></td><td>{l.priority}</td><td><div className="flex gap-1"><button className="btn" title="Call" onClick={()=>setCallLead(l)}><Phone size={15}/></button><button className="btn" title="WhatsApp" onClick={()=>setPhaseLead(l)}><MessageCircle size={15}/></button><button className="btn" title="Follow-up" onClick={()=>{setSelected(l);setShowFollowup(true)}}><CalendarDays size={15}/></button></div></td></tr>)}</tbody></table>{busy&&<div className="p-5 muted">Loading…</div>}{!busy&&!filtered.length&&<div className="p-8 text-center muted">No leads found.</div>}<div className="p-3 border-t border-slate-800 flex justify-between text-xs muted"><span>{filtered.length} leads</span><div className="flex gap-2"><button className="btn" disabled={page<=1} onClick={()=>setPage(page-1)}>Prev</button><span className="pt-2">Page {page}/{Math.max(1,Math.ceil(filtered.length/50))}</span><button className="btn" disabled={page>=Math.max(1,Math.ceil(filtered.length/50))} onClick={()=>setPage(page+1)}>Next</button></div></div></div></section>}

   {tab==="folders"&&<section className="card p-5"><div className="flex justify-between mb-4"><h2 className="font-semibold">Folders</h2><button className="btn btn-primary" onClick={()=>setShowFolder(true)}><Plus size={15}/>Create</button></div>{folders.map(f=><div key={f.id} className="border-b border-slate-800 py-3 flex justify-between"><div><div>{f.name}</div><div className="muted text-xs">{leads.filter(l=>l.folder_id===f.id).length} leads</div></div></div>)}</section>}

   {tab==="followups"&&<section className="card p-5"><h2 className="font-semibold mb-4">Follow-ups</h2>{followups.map(f=><div key={f.id} className="border-b border-slate-800 py-3 flex justify-between"><div><div>{f.title}</div><div className="muted text-xs">{new Date(f.scheduled_at).toLocaleString("en-IN")}</div></div><div className="flex gap-1"><button className="btn" onClick={()=>complete(f)}>{f.completed?"Reopen":"Complete"}</button><button className="btn" onClick={()=>startEditFollowup(f)}><Edit3 size={14}/></button></div></div>)}</section>}

   {tab==="templates"&&<section className="card p-5"><div className="flex justify-between mb-4"><h2 className="font-semibold">Message Templates</h2><button className="btn btn-primary" onClick={()=>setShowTemplate(true)}><Plus size={15}/>Phase</button></div>{templates.map(t=><div key={t.id} className="border-b border-slate-800 py-3"><div className="flex justify-between gap-3"><div><b>Phase {t.phase_number} · {t.title}</b><div className="muted text-xs">{folders.find(f=>f.id===t.folder_id)?.name||"All folders"}</div><div className="muted text-sm mt-1 whitespace-pre-wrap">{t.message}</div></div><div className="flex gap-1"><button className="btn" onClick={()=>startEditTemplate(t)}><Edit3 size={14}/></button><button className="btn" onClick={()=>deleteTemplate(t)}><Trash2 size={14}/></button></div></div></div>)}</section>}

   {tab==="activity"&&<section className="card p-5"><h2 className="font-semibold mb-4">Recent Activity</h2>{activities.map(a=><div key={a.id} className="py-3 border-b border-slate-800"><div className="flex gap-2"><ActivityIcon size={15}/>{a.description}</div><div className="muted text-xs mt-1">{new Date(a.created_at).toLocaleString("en-IN")}</div></div>)}</section>}
  </main></div>

 {selected&&<div className="fixed inset-0 bg-black/70 z-40" onClick={()=>setSelected(null)}><aside className="absolute right-0 top-0 h-full w-full max-w-xl bg-[#0b1017] border-l border-slate-800 p-6 overflow-auto" onClick={e=>e.stopPropagation()}><div className="flex justify-between"><div><h2 className="text-xl font-semibold">{selected.business_name}</h2><div className="muted">{selected.client_name||selected.email||"No contact name"}</div></div><button className="btn" onClick={()=>setSelected(null)}>Close</button></div><div className="grid grid-cols-2 sm:grid-cols-4 gap-2 mt-6"><button className="btn" onClick={()=>setCallLead(selected)}><Phone size={15}/>Call</button><button className="btn" onClick={()=>setPhaseLead(selected)}><MessageCircle size={15}/>WhatsApp</button><button className="btn" onClick={()=>setShowFollowup(true)}><CalendarDays size={15}/>Follow-up</button><button className="btn" onClick={()=>window.open(selected.website||"","_blank")}><ExternalLink size={15}/>Website</button></div><div className="grid grid-cols-2 gap-3 mt-4"><div className="card p-3"><div className="muted text-xs">Outreach</div><div className="font-semibold">{sentCount(selected.id)}/{templates.filter(t=>t.folder_id===selected.folder_id||t.folder_id===null).length}</div></div><div className="card p-3"><div className="muted text-xs">Calls</div><div className="font-semibold">{selected.call_attempts||0}</div></div></div><div className="mt-6"><h3 className="font-medium mb-2">Notes</h3><textarea className="field min-h-24" value={note} onChange={e=>setNote(e.target.value)} placeholder="Add a note…"/><button className="btn btn-primary mt-2" onClick={saveNote}>Save note</button></div><div className="mt-6"><h3 className="font-medium mb-2">Follow-ups</h3>{followups.filter(f=>f.lead_id===selected.id).map(f=><div key={f.id} className="py-2 border-b border-slate-800 text-sm flex justify-between"><span>{f.title} · {new Date(f.scheduled_at).toLocaleString("en-IN")}</span><button className="btn" onClick={()=>startEditFollowup(f)}><Edit3 size={13}/></button></div>)}<button className="btn mt-3" onClick={()=>setShowFollowup(true)}><Plus size={15}/>Schedule</button></div><div className="mt-6"><h3 className="font-medium mb-2">Notes history</h3>{notes.filter(n=>n.lead_id===selected.id).map(n=><div key={n.id} className="py-2 border-b border-slate-800 text-sm"><div>{n.content}</div><div className="muted text-xs">{new Date(n.created_at).toLocaleString("en-IN")}</div></div>)}</div><div className="mt-6"><h3 className="font-medium mb-2">WhatsApp history</h3>{progress.filter(p=>p.lead_id===selected.id).map(p=><div key={p.id} className="py-2 border-b border-slate-800 text-sm flex justify-between"><span>Phase {p.phase_number} · {p.state}</span>{p.state==="opened"&&<button className="btn" onClick={()=>confirmSent(p)}>Confirm sent</button>}</div>)}</div></aside></div>}

 {phaseLead&&<div className="fixed inset-0 bg-black/70 z-50 grid place-items-center p-4" onClick={()=>setPhaseLead(null)}><div className="card p-6 w-full max-w-lg" onClick={e=>e.stopPropagation()}><h2 className="text-xl font-semibold">WhatsApp Outreach</h2><p className="muted text-sm mt-1">{phaseLead.business_name} · {phaseLead.whatsapp||phaseLead.phone||"No number"}</p><div className="grid gap-2 mt-5">{templates.filter(t=>t.folder_id===phaseLead.folder_id||t.folder_id===null).map(t=><div key={t.id} className="card p-3"><button className="btn w-full text-left" onClick={()=>openWA(phaseLead,t)}>Phase {t.phase_number} — {t.title}<div className="muted text-xs truncate">{personalize(t.message,phaseLead)}</div></button>{progress.filter(p=>p.lead_id===phaseLead.id&&p.template_id===t.id).slice(-1).map(p=><div key={p.id} className="flex justify-between items-center mt-2 text-xs"><span className={p.state==="confirmed_sent"?"text-green-400":"text-yellow-300"}>{p.state==="confirmed_sent"?"Sent":"Opened"}</span>{p.state==="opened"&&<button className="btn" onClick={()=>confirmSent(p)}>Confirm sent</button>}</div>)}</div>)}{!templates.length&&<div className="muted">Create a message template first.</div>}</div><button className="btn mt-5" onClick={()=>setPhaseLead(null)}>Close</button></div></div>}

 {callLead&&<div className="fixed inset-0 bg-black/70 z-50 grid place-items-center p-4" onClick={()=>setCallLead(null)}><div className="card p-6 w-full max-w-md" onClick={e=>e.stopPropagation()}><h2 className="text-lg font-semibold">Call outcome</h2><p className="muted text-sm mt-1">{callLead.business_name} · Attempt #{(callLead.call_attempts||0)+1}</p><div className="grid gap-2 mt-4">{outcomes.map(o=><button key={o} className="btn text-left" onClick={()=>{call(callLead,o);setCallLead(null)}}>{o}</button>)}</div><button className="btn mt-3 w-full" onClick={()=>setCallLead(null)}>Cancel</button></div></div>}
 {showFolder&&<div className="fixed inset-0 bg-black/70 z-50 grid place-items-center p-4"><div className="card p-6 w-full max-w-md"><h2 className="text-lg font-semibold">Create folder</h2><input className="field mt-4" placeholder="e.g. Dental" value={newFolder} onChange={e=>setNewFolder(e.target.value)}/><div className="flex gap-2 mt-4"><button className="btn btn-primary" onClick={addFolder}>Create</button><button className="btn" onClick={()=>setShowFolder(false)}>Cancel</button></div></div></div>}

 {showTemplate&&<div className="fixed inset-0 bg-black/70 z-50 grid place-items-center p-4"><div className="card p-6 w-full max-w-lg"><h2 className="text-lg font-semibold">{editTemplate?"Edit WhatsApp phase":"New WhatsApp phase"}</h2><div className="grid gap-3 mt-4"><select className="field" value={newTemplate.folder_id} onChange={e=>setNewTemplate({...newTemplate,folder_id:e.target.value})}><option value="">All folders</option>{folders.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select><input className="field" placeholder="Title" value={newTemplate.title} onChange={e=>setNewTemplate({...newTemplate,title:e.target.value})}/><input className="field" type="number" min="1" placeholder="Phase number" value={newTemplate.phase_number} onChange={e=>setNewTemplate({...newTemplate,phase_number:+e.target.value})}/><textarea className="field min-h-32" placeholder="Message. Variables: {{client_name}} {{business_name}} {{city}} {{category}}" value={newTemplate.message} onChange={e=>setNewTemplate({...newTemplate,message:e.target.value})}/></div><div className="flex gap-2 mt-4"><button className="btn btn-primary" onClick={addTemplate}>Save</button><button className="btn" onClick={()=>setShowTemplate(false)}>Cancel</button></div></div></div>}

 {showFollowup&&selected&&<div className="fixed inset-0 bg-black/70 z-50 grid place-items-center p-4"><div className="card p-6 w-full max-w-md"><h2 className="text-lg font-semibold">Schedule follow-up</h2><div className="grid gap-3 mt-4"><input className="field" placeholder="Title" value={follow.title} onChange={e=>setFollow({...follow,title:e.target.value})}/><textarea className="field" placeholder="Description" value={follow.description} onChange={e=>setFollow({...follow,description:e.target.value})}/><input className="field" type="datetime-local" value={follow.scheduled_at} onChange={e=>setFollow({...follow,scheduled_at:e.target.value})}/></div><div className="flex gap-2 mt-4"><button className="btn btn-primary" onClick={addFollow}>{editFollowup?"Update":"Schedule"}</button><button className="btn" onClick={()=>setShowFollowup(false)}>Cancel</button></div></div></div>}

 {showImport&&<div className="fixed inset-0 bg-black/70 z-50 grid place-items-center p-4"><div className="card p-6 w-full max-w-md"><h2 className="text-lg font-semibold">Import Excel / CSV</h2><p className="muted text-sm mt-1">Duplicates are skipped using phone, WhatsApp, email, or business + city.</p><input ref={input} className="hidden" type="file" accept=".csv,.xlsx,.xls" onChange={e=>{const f=e.target.files?.[0];if(f)importFile(f)}}/><button className="btn btn-primary mt-5 w-full" onClick={()=>input.current?.click()}><Upload size={16}/>Choose file</button>{importRows.length>0&&<div className="mt-4"><div className="muted text-xs mb-2">Preview: {importRows.length} rows · first 5 shown</div><select className="field" value={importMode} onChange={e=>setImportMode(e.target.value)}><option value="skip">Skip duplicates</option><option value="update">Update duplicates</option><option value="new">Always create new</option></select><div className="overflow-auto mt-3 max-h-48"><table className="w-full text-xs"><thead><tr><th className="text-left p-2">Business</th><th className="text-left p-2">Phone</th><th className="text-left p-2">City</th></tr></thead><tbody>{importRows.slice(0,5).map((r,i)=><tr key={i} className="border-t border-slate-800"><td className="p-2">{val(r,Object.keys(r).find(h=>h.toLowerCase().replace(/[^a-z0-9]/g,"_").includes("business_name"))||"")}</td><td className="p-2">{val(r,Object.keys(r).find(h=>h.toLowerCase().includes("phone"))||"")}</td><td className="p-2">{val(r,Object.keys(r).find(h=>h.toLowerCase().includes("city"))||"")}</td></tr>)}</tbody></table></div><button className="btn btn-primary mt-3 w-full" onClick={async()=>{let added=0,updated=0,skipped=0;for(const r of importRows){const norm:any={};for(const k of fields){const found=Object.keys(r).find(h=>h.toLowerCase().replace(/[^a-z0-9]/g,"_").includes(k));norm[k]=found?val(r,found):""}if(!norm.business_name){skipped++;continue}const duplicate=leads.find(l=>(norm.phone&&l.phone===norm.phone)||(norm.whatsapp&&l.whatsapp===norm.whatsapp)||(norm.email&&l.email===norm.email)||(norm.business_name.toLowerCase()===l.business_name.toLowerCase()&&norm.city&&l.city===norm.city));if(duplicate&&importMode==="skip"){skipped++;continue}if(duplicate&&importMode==="update"){await supabase.from("leads").update(norm).eq("id",duplicate.id);updated++;continue}const {error}=await supabase.from("leads").insert({...norm,user_id:user.id,folder_id:folder||null});if(!error)added++}setImportRows([]);setShowImport(false);await load(user);notify(`Import complete: ${added} added, ${updated} updated, ${skipped} skipped`);}}>Import {importRows.length} rows</button></div>}<button className="btn mt-2 w-full" onClick={()=>{setImportRows([]);setShowImport(false)}}>Cancel</button></div></div>}
 </div>
}